// Mocks generated by Mockito 5.4.6 from annotations
// in greenfield/test/mocks/mock_settings_storage_service.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:greenfield/core/services/settings_storage_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [SettingsStorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSettingsStorageService extends _i1.Mock
    implements _i2.SettingsStorageService {
  MockSettingsStorageService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<bool> hasAdminPassword() =>
      (super.noSuchMethod(
            Invocation.method(#hasAdminPassword, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<void> setAdminPassword(String? password) =>
      (super.noSuchMethod(
            Invocation.method(#setAdminPassword, [password]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<bool> verifyAdminPassword(String? password) =>
      (super.noSuchMethod(
            Invocation.method(#verifyAdminPassword, [password]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<String?> getClaudeApiKey() =>
      (super.noSuchMethod(
            Invocation.method(#getClaudeApiKey, []),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i3.Future<void> setClaudeApiKey(String? value) =>
      (super.noSuchMethod(
            Invocation.method(#setClaudeApiKey, [value]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> setClaudeModel(String? value) =>
      (super.noSuchMethod(
            Invocation.method(#setClaudeModel, [value]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> setMcpServerUrl(String? value) =>
      (super.noSuchMethod(
            Invocation.method(#setMcpServerUrl, [value]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<String?> getGoogleChatWebhook() =>
      (super.noSuchMethod(
            Invocation.method(#getGoogleChatWebhook, []),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i3.Future<void> setGoogleChatWebhook(String? value) =>
      (super.noSuchMethod(
            Invocation.method(#setGoogleChatWebhook, [value]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<String?> getDiscordBotToken() =>
      (super.noSuchMethod(
            Invocation.method(#getDiscordBotToken, []),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i3.Future<void> setDiscordBotToken(String? value) =>
      (super.noSuchMethod(
            Invocation.method(#setDiscordBotToken, [value]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<String?> getSlackAppToken() =>
      (super.noSuchMethod(
            Invocation.method(#getSlackAppToken, []),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i3.Future<void> setSlackAppToken(String? value) =>
      (super.noSuchMethod(
            Invocation.method(#setSlackAppToken, [value]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> setEnableQuestGeneration(bool? value) =>
      (super.noSuchMethod(
            Invocation.method(#setEnableQuestGeneration, [value]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> setEnableChatBots(bool? value) =>
      (super.noSuchMethod(
            Invocation.method(#setEnableChatBots, [value]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> setEnableNotifications(bool? value) =>
      (super.noSuchMethod(
            Invocation.method(#setEnableNotifications, [value]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> setEnableRecurringEvents(bool? value) =>
      (super.noSuchMethod(
            Invocation.method(#setEnableRecurringEvents, [value]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> setMaxFellowshipSize(int? value) =>
      (super.noSuchMethod(
            Invocation.method(#setMaxFellowshipSize, [value]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> setXpMultiplier(double? value) =>
      (super.noSuchMethod(
            Invocation.method(#setXpMultiplier, [value]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> setDailyQuestResetHour(int? value) =>
      (super.noSuchMethod(
            Invocation.method(#setDailyQuestResetHour, [value]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> setDebugMode(bool? value) =>
      (super.noSuchMethod(
            Invocation.method(#setDebugMode, [value]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> clearAll() =>
      (super.noSuchMethod(
            Invocation.method(#clearAll, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
