// Mocks generated by Mockito 5.4.6 from annotations
// in greenfield/test/mocks/mock_health_check_services.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:greenfield/core/services/health_check/claude_health_check_service.dart'
    as _i3;
import 'package:greenfield/core/services/health_check/discord_health_check_service.dart'
    as _i6;
import 'package:greenfield/core/services/health_check/google_chat_health_check_service.dart'
    as _i8;
import 'package:greenfield/core/services/health_check/health_check_result.dart'
    as _i2;
import 'package:greenfield/core/services/health_check/slack_health_check_service.dart'
    as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeHealthCheckResult_0 extends _i1.SmartFake
    implements _i2.HealthCheckResult {
  _FakeHealthCheckResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ClaudeHealthCheckService].
///
/// See the documentation for Mockito's code generation for more information.
class MockClaudeHealthCheckService extends _i1.Mock
    implements _i3.ClaudeHealthCheckService {
  MockClaudeHealthCheckService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get serviceName =>
      (super.noSuchMethod(
            Invocation.getter(#serviceName),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#serviceName),
            ),
          )
          as String);

  @override
  _i5.Future<_i2.HealthCheckResult> validateFormat(String? apiKey) =>
      (super.noSuchMethod(
            Invocation.method(#validateFormat, [apiKey]),
            returnValue: _i5.Future<_i2.HealthCheckResult>.value(
              _FakeHealthCheckResult_0(
                this,
                Invocation.method(#validateFormat, [apiKey]),
              ),
            ),
          )
          as _i5.Future<_i2.HealthCheckResult>);

  @override
  _i5.Future<_i2.HealthCheckResult> testConnectivity(
    String? apiKey, {
    Duration? timeout = const Duration(seconds: 10),
  }) =>
      (super.noSuchMethod(
            Invocation.method(#testConnectivity, [apiKey], {#timeout: timeout}),
            returnValue: _i5.Future<_i2.HealthCheckResult>.value(
              _FakeHealthCheckResult_0(
                this,
                Invocation.method(
                  #testConnectivity,
                  [apiKey],
                  {#timeout: timeout},
                ),
              ),
            ),
          )
          as _i5.Future<_i2.HealthCheckResult>);

  @override
  _i5.Future<_i2.HealthCheckResult> validatePermissions(String? apiKey) =>
      (super.noSuchMethod(
            Invocation.method(#validatePermissions, [apiKey]),
            returnValue: _i5.Future<_i2.HealthCheckResult>.value(
              _FakeHealthCheckResult_0(
                this,
                Invocation.method(#validatePermissions, [apiKey]),
              ),
            ),
          )
          as _i5.Future<_i2.HealthCheckResult>);

  @override
  _i5.Future<_i2.HealthCheckResult> runAllChecks(String? value) =>
      (super.noSuchMethod(
            Invocation.method(#runAllChecks, [value]),
            returnValue: _i5.Future<_i2.HealthCheckResult>.value(
              _FakeHealthCheckResult_0(
                this,
                Invocation.method(#runAllChecks, [value]),
              ),
            ),
          )
          as _i5.Future<_i2.HealthCheckResult>);
}

/// A class which mocks [DiscordHealthCheckService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDiscordHealthCheckService extends _i1.Mock
    implements _i6.DiscordHealthCheckService {
  MockDiscordHealthCheckService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get serviceName =>
      (super.noSuchMethod(
            Invocation.getter(#serviceName),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#serviceName),
            ),
          )
          as String);

  @override
  _i5.Future<_i2.HealthCheckResult> validateFormat(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#validateFormat, [token]),
            returnValue: _i5.Future<_i2.HealthCheckResult>.value(
              _FakeHealthCheckResult_0(
                this,
                Invocation.method(#validateFormat, [token]),
              ),
            ),
          )
          as _i5.Future<_i2.HealthCheckResult>);

  @override
  _i5.Future<_i2.HealthCheckResult> testConnectivity(
    String? token, {
    Duration? timeout = const Duration(seconds: 10),
  }) =>
      (super.noSuchMethod(
            Invocation.method(#testConnectivity, [token], {#timeout: timeout}),
            returnValue: _i5.Future<_i2.HealthCheckResult>.value(
              _FakeHealthCheckResult_0(
                this,
                Invocation.method(
                  #testConnectivity,
                  [token],
                  {#timeout: timeout},
                ),
              ),
            ),
          )
          as _i5.Future<_i2.HealthCheckResult>);

  @override
  _i5.Future<_i2.HealthCheckResult> validatePermissions(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#validatePermissions, [token]),
            returnValue: _i5.Future<_i2.HealthCheckResult>.value(
              _FakeHealthCheckResult_0(
                this,
                Invocation.method(#validatePermissions, [token]),
              ),
            ),
          )
          as _i5.Future<_i2.HealthCheckResult>);

  @override
  _i5.Future<_i2.HealthCheckResult> runAllChecks(String? value) =>
      (super.noSuchMethod(
            Invocation.method(#runAllChecks, [value]),
            returnValue: _i5.Future<_i2.HealthCheckResult>.value(
              _FakeHealthCheckResult_0(
                this,
                Invocation.method(#runAllChecks, [value]),
              ),
            ),
          )
          as _i5.Future<_i2.HealthCheckResult>);
}

/// A class which mocks [SlackHealthCheckService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSlackHealthCheckService extends _i1.Mock
    implements _i7.SlackHealthCheckService {
  MockSlackHealthCheckService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get serviceName =>
      (super.noSuchMethod(
            Invocation.getter(#serviceName),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#serviceName),
            ),
          )
          as String);

  @override
  _i5.Future<_i2.HealthCheckResult> validateFormat(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#validateFormat, [token]),
            returnValue: _i5.Future<_i2.HealthCheckResult>.value(
              _FakeHealthCheckResult_0(
                this,
                Invocation.method(#validateFormat, [token]),
              ),
            ),
          )
          as _i5.Future<_i2.HealthCheckResult>);

  @override
  _i5.Future<_i2.HealthCheckResult> testConnectivity(
    String? token, {
    Duration? timeout = const Duration(seconds: 10),
  }) =>
      (super.noSuchMethod(
            Invocation.method(#testConnectivity, [token], {#timeout: timeout}),
            returnValue: _i5.Future<_i2.HealthCheckResult>.value(
              _FakeHealthCheckResult_0(
                this,
                Invocation.method(
                  #testConnectivity,
                  [token],
                  {#timeout: timeout},
                ),
              ),
            ),
          )
          as _i5.Future<_i2.HealthCheckResult>);

  @override
  _i5.Future<_i2.HealthCheckResult> validatePermissions(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#validatePermissions, [token]),
            returnValue: _i5.Future<_i2.HealthCheckResult>.value(
              _FakeHealthCheckResult_0(
                this,
                Invocation.method(#validatePermissions, [token]),
              ),
            ),
          )
          as _i5.Future<_i2.HealthCheckResult>);

  @override
  _i5.Future<_i2.HealthCheckResult> runAllChecks(String? value) =>
      (super.noSuchMethod(
            Invocation.method(#runAllChecks, [value]),
            returnValue: _i5.Future<_i2.HealthCheckResult>.value(
              _FakeHealthCheckResult_0(
                this,
                Invocation.method(#runAllChecks, [value]),
              ),
            ),
          )
          as _i5.Future<_i2.HealthCheckResult>);
}

/// A class which mocks [GoogleChatHealthCheckService].
///
/// See the documentation for Mockito's code generation for more information.
class MockGoogleChatHealthCheckService extends _i1.Mock
    implements _i8.GoogleChatHealthCheckService {
  MockGoogleChatHealthCheckService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get serviceName =>
      (super.noSuchMethod(
            Invocation.getter(#serviceName),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#serviceName),
            ),
          )
          as String);

  @override
  _i5.Future<_i2.HealthCheckResult> validateFormat(String? webhookUrl) =>
      (super.noSuchMethod(
            Invocation.method(#validateFormat, [webhookUrl]),
            returnValue: _i5.Future<_i2.HealthCheckResult>.value(
              _FakeHealthCheckResult_0(
                this,
                Invocation.method(#validateFormat, [webhookUrl]),
              ),
            ),
          )
          as _i5.Future<_i2.HealthCheckResult>);

  @override
  _i5.Future<_i2.HealthCheckResult> testConnectivity(
    String? webhookUrl, {
    Duration? timeout = const Duration(seconds: 10),
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #testConnectivity,
              [webhookUrl],
              {#timeout: timeout},
            ),
            returnValue: _i5.Future<_i2.HealthCheckResult>.value(
              _FakeHealthCheckResult_0(
                this,
                Invocation.method(
                  #testConnectivity,
                  [webhookUrl],
                  {#timeout: timeout},
                ),
              ),
            ),
          )
          as _i5.Future<_i2.HealthCheckResult>);

  @override
  _i5.Future<_i2.HealthCheckResult> validatePermissions(String? webhookUrl) =>
      (super.noSuchMethod(
            Invocation.method(#validatePermissions, [webhookUrl]),
            returnValue: _i5.Future<_i2.HealthCheckResult>.value(
              _FakeHealthCheckResult_0(
                this,
                Invocation.method(#validatePermissions, [webhookUrl]),
              ),
            ),
          )
          as _i5.Future<_i2.HealthCheckResult>);

  @override
  _i5.Future<_i2.HealthCheckResult> runAllChecks(String? value) =>
      (super.noSuchMethod(
            Invocation.method(#runAllChecks, [value]),
            returnValue: _i5.Future<_i2.HealthCheckResult>.value(
              _FakeHealthCheckResult_0(
                this,
                Invocation.method(#runAllChecks, [value]),
              ),
            ),
          )
          as _i5.Future<_i2.HealthCheckResult>);
}
